name: modelrecords
channels:
  - conda-forge
  - defaults
dependencies:
  - pip:
    - pyyaml
    - semantic_version
    - jinja2
    - omegaconf
    - requests
    - PyPDF2
    - openai
    - pelican[markdown]
    - invoke
    - livereload
    - pytailwindcss
